# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import autocare_pb2 as autocare__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autocare_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectorStub(object):
    """DX API Serivce

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddInference = channel.unary_unary(
                '/autocare.Detector/AddInference',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceRes.FromString,
                _registered_method=True)
        self.RemoveInference = channel.unary_unary(
                '/autocare.Detector/RemoveInference',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceRes.FromString,
                _registered_method=True)
        self.RemoveInferenceAll = channel.unary_unary(
                '/autocare.Detector/RemoveInferenceAll',
                request_serializer=autocare__pb2.AppReq.SerializeToString,
                response_deserializer=autocare__pb2.AppRes.FromString,
                _registered_method=True)
        self.UpdateInference = channel.unary_unary(
                '/autocare.Detector/UpdateInference',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceRes.FromString,
                _registered_method=True)
        self.InstallApp = channel.stream_unary(
                '/autocare.Detector/InstallApp',
                request_serializer=autocare__pb2.AppReq.SerializeToString,
                response_deserializer=autocare__pb2.AppRes.FromString,
                _registered_method=True)
        self.UninstallApp = channel.unary_unary(
                '/autocare.Detector/UninstallApp',
                request_serializer=autocare__pb2.AppReq.SerializeToString,
                response_deserializer=autocare__pb2.AppRes.FromString,
                _registered_method=True)
        self.GetAppList = channel.unary_unary(
                '/autocare.Detector/GetAppList',
                request_serializer=autocare__pb2.AppReq.SerializeToString,
                response_deserializer=autocare__pb2.AppList.FromString,
                _registered_method=True)
        self.GetInferenceList = channel.unary_unary(
                '/autocare.Detector/GetInferenceList',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceList.FromString,
                _registered_method=True)
        self.GetInferenceStatus = channel.unary_unary(
                '/autocare.Detector/GetInferenceStatus',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceRes.FromString,
                _registered_method=True)
        self.GetInferenceStatusAll = channel.unary_unary(
                '/autocare.Detector/GetInferenceStatusAll',
                request_serializer=autocare__pb2.AppReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceResList.FromString,
                _registered_method=True)
        self.RequestPreviewImage = channel.unary_unary(
                '/autocare.Detector/RequestPreviewImage',
                request_serializer=autocare__pb2.InferenceReq.SerializeToString,
                response_deserializer=autocare__pb2.InferenceRes.FromString,
                _registered_method=True)
        self.LicenseActivation = channel.unary_unary(
                '/autocare.Detector/LicenseActivation',
                request_serializer=autocare__pb2.LicReq.SerializeToString,
                response_deserializer=autocare__pb2.LicRes.FromString,
                _registered_method=True)
        self.LicenseDeactivation = channel.unary_unary(
                '/autocare.Detector/LicenseDeactivation',
                request_serializer=autocare__pb2.LicReq.SerializeToString,
                response_deserializer=autocare__pb2.LicRes.FromString,
                _registered_method=True)
        self.LicenseActivate = channel.unary_unary(
                '/autocare.Detector/LicenseActivate',
                request_serializer=autocare__pb2.LicReq.SerializeToString,
                response_deserializer=autocare__pb2.LicRes.FromString,
                _registered_method=True)
        self.StartStreaming = channel.unary_unary(
                '/autocare.Detector/StartStreaming',
                request_serializer=autocare__pb2.StreamingReq.SerializeToString,
                response_deserializer=autocare__pb2.StreamingRes.FromString,
                _registered_method=True)
        self.StopStreaming = channel.unary_unary(
                '/autocare.Detector/StopStreaming',
                request_serializer=autocare__pb2.StreamingReq.SerializeToString,
                response_deserializer=autocare__pb2.StreamingRes.FromString,
                _registered_method=True)
        self.GetDx = channel.unary_unary(
                '/autocare.Detector/GetDx',
                request_serializer=autocare__pb2.Empty.SerializeToString,
                response_deserializer=autocare__pb2.Dx.FromString,
                _registered_method=True)


class DetectorServicer(object):
    """DX API Serivce

    """

    def AddInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveInferenceAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallApp(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UninstallApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceStatusAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPreviewImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseActivation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseDeactivation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseActivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddInference': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInference,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceRes.SerializeToString,
            ),
            'RemoveInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveInference,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceRes.SerializeToString,
            ),
            'RemoveInferenceAll': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveInferenceAll,
                    request_deserializer=autocare__pb2.AppReq.FromString,
                    response_serializer=autocare__pb2.AppRes.SerializeToString,
            ),
            'UpdateInference': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInference,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceRes.SerializeToString,
            ),
            'InstallApp': grpc.stream_unary_rpc_method_handler(
                    servicer.InstallApp,
                    request_deserializer=autocare__pb2.AppReq.FromString,
                    response_serializer=autocare__pb2.AppRes.SerializeToString,
            ),
            'UninstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.UninstallApp,
                    request_deserializer=autocare__pb2.AppReq.FromString,
                    response_serializer=autocare__pb2.AppRes.SerializeToString,
            ),
            'GetAppList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppList,
                    request_deserializer=autocare__pb2.AppReq.FromString,
                    response_serializer=autocare__pb2.AppList.SerializeToString,
            ),
            'GetInferenceList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceList,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceList.SerializeToString,
            ),
            'GetInferenceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceStatus,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceRes.SerializeToString,
            ),
            'GetInferenceStatusAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceStatusAll,
                    request_deserializer=autocare__pb2.AppReq.FromString,
                    response_serializer=autocare__pb2.InferenceResList.SerializeToString,
            ),
            'RequestPreviewImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPreviewImage,
                    request_deserializer=autocare__pb2.InferenceReq.FromString,
                    response_serializer=autocare__pb2.InferenceRes.SerializeToString,
            ),
            'LicenseActivation': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseActivation,
                    request_deserializer=autocare__pb2.LicReq.FromString,
                    response_serializer=autocare__pb2.LicRes.SerializeToString,
            ),
            'LicenseDeactivation': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseDeactivation,
                    request_deserializer=autocare__pb2.LicReq.FromString,
                    response_serializer=autocare__pb2.LicRes.SerializeToString,
            ),
            'LicenseActivate': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseActivate,
                    request_deserializer=autocare__pb2.LicReq.FromString,
                    response_serializer=autocare__pb2.LicRes.SerializeToString,
            ),
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=autocare__pb2.StreamingReq.FromString,
                    response_serializer=autocare__pb2.StreamingRes.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=autocare__pb2.StreamingReq.FromString,
                    response_serializer=autocare__pb2.StreamingRes.SerializeToString,
            ),
            'GetDx': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDx,
                    request_deserializer=autocare__pb2.Empty.FromString,
                    response_serializer=autocare__pb2.Dx.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autocare.Detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autocare.Detector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Detector(object):
    """DX API Serivce

    """

    @staticmethod
    def AddInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/AddInference',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/RemoveInference',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveInferenceAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/RemoveInferenceAll',
            autocare__pb2.AppReq.SerializeToString,
            autocare__pb2.AppRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/UpdateInference',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallApp(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/autocare.Detector/InstallApp',
            autocare__pb2.AppReq.SerializeToString,
            autocare__pb2.AppRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UninstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/UninstallApp',
            autocare__pb2.AppReq.SerializeToString,
            autocare__pb2.AppRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/GetAppList',
            autocare__pb2.AppReq.SerializeToString,
            autocare__pb2.AppList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/GetInferenceList',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/GetInferenceStatus',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceStatusAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/GetInferenceStatusAll',
            autocare__pb2.AppReq.SerializeToString,
            autocare__pb2.InferenceResList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPreviewImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/RequestPreviewImage',
            autocare__pb2.InferenceReq.SerializeToString,
            autocare__pb2.InferenceRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LicenseActivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/LicenseActivation',
            autocare__pb2.LicReq.SerializeToString,
            autocare__pb2.LicRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LicenseDeactivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/LicenseDeactivation',
            autocare__pb2.LicReq.SerializeToString,
            autocare__pb2.LicRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LicenseActivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/LicenseActivate',
            autocare__pb2.LicReq.SerializeToString,
            autocare__pb2.LicRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/StartStreaming',
            autocare__pb2.StreamingReq.SerializeToString,
            autocare__pb2.StreamingRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/StopStreaming',
            autocare__pb2.StreamingReq.SerializeToString,
            autocare__pb2.StreamingRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autocare.Detector/GetDx',
            autocare__pb2.Empty.SerializeToString,
            autocare__pb2.Dx.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
